library(robotstxt)
path<-paths_allowed("https://stats.espncricinfo.com/ci/engine/records/individual/list_captains.html?class=2;id=6;type=team")
library(rvest)
link<-"https://stats.espncricinfo.com/ci/engine/records/individual/list_captains.html?class=2;id=6;type=team"
web<-read_html(link)
library(dplyr)
captain_name<-web%>%html_nodes(".data1 .left:nth-child(1)")%>%html_text()
View(captain_name)
match_played<-web%>%html_nodes(".data1 .padAst")%>%html_text()
View(match_played)
match_won<-web%>%html_nodes(".padAst+ td")%>%html_text()
View(match_won)
match_lost<-web%>%html_nodes("td:nth-child(5)")%>%html_text()
View(match_lost)
cricket_stats<-data.frame(captain_name,match_played,match_won,match_lost)
View(cricket_stats)
write.csv(cricket_stats,"cricket.csv")
